Troubleshoot YAML file

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -13,8 +13,6 @@ jobs:
   validate:
     runs-on: ubuntu-latest
     name: terraform fmt check
-    outputs:
-      CHECK_STATUS: "${{ env.CHECK_STATUS }}"
     steps:
       - uses: actions/checkout@v3
         with:
@@ -32,8 +30,6 @@ jobs:
         run: |
           set -e
 
-          echo "CHECK_STATUS=0" >> $GITHUB_ENV
-
           for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
             echo "Checking terraform fmt on ${changed_file}..."
 
@@ -43,10 +39,7 @@ jobs:
 
               if [[ $FMT_STATUS -ne 0 ]]; then
                 echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
-                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+                exit 1 # Exit immediately on failure
               fi
             fi
           done
-      - name: Process check
-        if: always()
-        run: exit $CHECK_STATUS
